import type { Session } from "@shared/types";

/**
 * Subset of the AABW catalog actually referenced by the landing personas
 * + alt paths. Inlined here so the landing has zero API dependency and the
 * voter funnel still works even if the backend is down.
 *
 * Keep in sync with apps/api/app/data/sessions.json — fields below mirror
 * that file 1:1 for the IDs we use here.
 */
export const DEMO_SESSIONS: Record<string, Session> = {
  "d1-anthropic-claude-intro": {
    id: "d1-anthropic-claude-intro",
    day: 1,
    start: "10:30",
    end: "12:00",
    venue: "Main Hall",
    partner: "Anthropic",
    title: "Building Agents with Claude: A Practical Kickoff",
    description:
      "Foundations for tool-use and agent loops with Claude. Hands-on starter.",
    tags: ["anthropic", "agents", "tool-use", "intro"],
    level: "intro",
    source: "mock",
    signup_url: null,
  },
  "d2-anthropic-tooluse": {
    id: "d2-anthropic-tooluse",
    day: 2,
    start: "10:00",
    end: "12:00",
    venue: "Workshop B",
    partner: "Anthropic",
    title: "Claude Tool Use: Patterns That Actually Work",
    description: "Real-world patterns + anti-patterns for production tool use.",
    tags: ["anthropic", "agents", "tool-use", "deep"],
    level: "deep",
    source: "mock",
    signup_url: null,
  },
  "d2-openai-realtime": {
    id: "d2-openai-realtime",
    day: 2,
    start: "10:00",
    end: "11:30",
    venue: "Workshop A",
    partner: "OpenAI",
    title: "Realtime API Workshop: Voice Agents in 90 Minutes",
    description: "Build a voice agent end-to-end with the Realtime API.",
    tags: ["openai", "voice", "agents", "intermediate"],
    level: "intermediate",
    source: "mock",
    signup_url: null,
  },
  "d2-anthropic-mcp": {
    id: "d2-anthropic-mcp",
    day: 2,
    start: "14:30",
    end: "16:00",
    venue: "Workshop B",
    partner: "Anthropic",
    title: "Building MCP Servers",
    description: "Ship your own MCP server. Stdio + HTTP transports.",
    tags: ["anthropic", "mcp", "tool-use", "deep"],
    level: "deep",
    source: "mock",
    signup_url: null,
  },
  "d2-langchain-langgraph": {
    id: "d2-langchain-langgraph",
    day: 2,
    start: "13:00",
    end: "14:30",
    venue: "Workshop C",
    partner: "LangChain",
    title: "LangGraph for Stateful Agents",
    description: "Stateful agent orchestration with LangGraph.",
    tags: ["langchain", "agents", "multi-agent", "memory"],
    level: "intermediate",
    source: "mock",
    signup_url: null,
  },
  "d2-mastra-framework": {
    id: "d2-mastra-framework",
    day: 2,
    start: "16:00",
    end: "17:30",
    venue: "Workshop A",
    partner: "Mastra",
    title: "Production Agents with Mastra",
    description: "Eval, deploy, monitor — production agent patterns.",
    tags: ["mastra", "agents", "eval", "deploy"],
    level: "intermediate",
    source: "mock",
    signup_url: null,
  },
  "d3-stripe-payments-agents": {
    id: "d3-stripe-payments-agents",
    day: 3,
    start: "11:30",
    end: "13:00",
    venue: "Main Hall",
    partner: "Stripe",
    title: "Payments for AI Agents",
    description: "Building agent flows that charge real money.",
    tags: ["stripe", "payments", "monetization", "agents"],
    level: "intermediate",
    source: "mock",
    signup_url: null,
  },
  "d3-apify-monetize-agents": {
    id: "d3-apify-monetize-agents",
    day: 3,
    start: "10:00",
    end: "11:30",
    venue: "Workshop A",
    partner: "Apify",
    title: "Build, Deploy and Monetize AI Agents",
    description: "From prototype to monetized agent product.",
    tags: ["apify", "agents", "deploy", "monetization"],
    level: "intermediate",
    source: "confirmed",
    signup_url: "https://bit.ly/aabw-apify",
  },
  "d3-anthropic-evals": {
    id: "d3-anthropic-evals",
    day: 3,
    start: "10:00",
    end: "11:30",
    venue: "Workshop B",
    partner: "Anthropic",
    title: "Eval Loops & Test Harnesses for Agents",
    description: "Catch regressions before your demo does.",
    tags: ["anthropic", "eval", "agents", "deep"],
    level: "deep",
    source: "mock",
    signup_url: null,
  },
  "d3-multi-agent-arch": {
    id: "d3-multi-agent-arch",
    day: 3,
    start: "13:00",
    end: "14:30",
    venue: "Workshop C",
    partner: "Anthropic",
    title: "Multi-Agent System Architecture",
    description: "Coordinator + sub-agents. When and how to split.",
    tags: ["anthropic", "multi-agent", "agents", "deep"],
    level: "deep",
    source: "mock",
    signup_url: null,
  },
  "d3-langchain-memory-patterns": {
    id: "d3-langchain-memory-patterns",
    day: 3,
    start: "13:00",
    end: "14:00",
    venue: "Workshop A",
    partner: "LangChain",
    title: "Agent Memory Patterns",
    description: "Short-term, long-term, and shared memory primitives.",
    tags: ["langchain", "memory", "agents", "intermediate"],
    level: "intermediate",
    source: "mock",
    signup_url: null,
  },
  "d3-google-beyond-autocomplete": {
    id: "d3-google-beyond-autocomplete",
    day: 3,
    start: "14:00",
    end: "15:30",
    venue: "Main Hall",
    partner: "Google",
    title: "Beyond Autocomplete: Agentic AI in the Enterprise",
    description: "Agentic UX patterns for production-grade products.",
    tags: ["google", "agents", "enterprise", "intermediate"],
    level: "intermediate",
    source: "mock",
    signup_url: null,
  },
  "d3-observability-langfuse": {
    id: "d3-observability-langfuse",
    day: 3,
    start: "16:30",
    end: "17:30",
    venue: "Workshop A",
    partner: "Langfuse",
    title: "Observability for AI Agents",
    description: "Traces, evals, and dashboards for live agents.",
    tags: ["langfuse", "observability", "eval", "intermediate"],
    level: "intermediate",
    source: "mock",
    signup_url: null,
  },
  "d4-clinic-tooluse": {
    id: "d4-clinic-tooluse",
    day: 4,
    start: "09:00",
    end: "10:30",
    venue: "Clinic Room A",
    partner: "Anthropic",
    title: "Clinic: Tool-Use Debugging",
    description: "Bring your broken tool calls — leave with working ones.",
    tags: ["anthropic", "tool-use", "agents", "deep"],
    level: "deep",
    source: "mock",
    signup_url: null,
  },
  "d4-clinic-evals": {
    id: "d4-clinic-evals",
    day: 4,
    start: "09:00",
    end: "10:30",
    venue: "Clinic Room B",
    partner: "OpenAI",
    title: "Clinic: Eval Design",
    description: "Pair-design eval suites with an expert.",
    tags: ["openai", "eval", "agents", "deep"],
    level: "deep",
    source: "mock",
    signup_url: null,
  },
  "d4-pitch-coaching": {
    id: "d4-pitch-coaching",
    day: 4,
    start: "14:00",
    end: "15:00",
    venue: "Main Hall",
    partner: null,
    title: "Demo Pitch Coaching",
    description: "Sharpen the 90-second story judges will hear.",
    tags: ["aabw", "pitch", "demo", "intermediate"],
    level: "intermediate",
    source: "mock",
    signup_url: null,
  },
  "d5-demo-day": {
    id: "d5-demo-day",
    day: 5,
    start: "14:00",
    end: "16:00",
    venue: "Main Hall",
    partner: null,
    title: "Demo Day Presentations",
    description: "Builders present. Judges score. You ship.",
    tags: ["aabw", "demo", "pitch", "intermediate"],
    level: "intermediate",
    source: "mock",
    signup_url: null,
  },
};
